### ISSUE TITLE
Online Repo not Available

### ISSUE THREAD

**Issue by Sircam7** [splunk/splunk-plugin-eclipse#2]
Hi,

I'm trying to install the Splunk Plugin for Eclipse on my Eclipse IDE but I can't manage to install it neither from the eclipse marketplace, nor from eclipse itself or any other links you posted for the documentation.
Looks like the online repo is not available, I'm getting this error:

> "The following solutions are not available: Splunk Plug-in for Eclipse 1.0.4 (id=com.splunk.project.java.feature.group, com.splunk.modularinput.java.feature.group, site=http://download.splunk.com/misc/sdk/eclipse/eclipse_plugin/)"

Any chances you can upload a .zip with the jar files (content.jar and artifacts.jar) to make a local installation?

Thank you!

Regards

**Comment by shakeelmohamed** [comment]
Hi @Sircam7, thanks for letting us know. I've filed DVPL-7290 internally and we will get this fixed ASAP.

**Comment by Sircam7** [comment]
Thank you very much @shakeelmohamed !! :)

Waiting for your feedback to install that plugin on my Eclipse.

Best regards

**Comment by shakeelmohamed** [comment]
Sorry for the delay here, we weren't able to reproduce the issue.
